entities:
  - file:
      path: /home/chenxq/boltzgen_me/LEADS-PEP_inputfiles/1B9J/1B9J_clean_protein.pdb
      include:
        - chain:
            id: A
            res_index: 32,33,34,35,109,397,401,436,404,416,415
      binding_types:
        - chain:
            id: A
            binding: 32,33,34,35,109,397,401,436,404,416,415

  - protein:
      id: B
      sequence: 12
