entities:
  - file:
      path: /home/chenxq/boltzgen_me/LEADS-PEP_inputfiles/3D1E/3D1E_clean_protein.pdb
      include:
        - chain:
            id: A
      binding_types:
        - chain:
            id: A
            binding: 152,155,172,174,175,176,177,242,247,323,344,346,360,362,363,364,365

  - protein:
      id: B
      sequence: 6
