entities:
  - file:
      path: /home/chenxq/boltzgen_me/LEADS-PEP_inputfiles/3IDG/3IDG_clean_protein.pdb
      include:
        - chain:
            id: B
      binding_types:
        - chain:
            id: B
            binding: 33,52,54,56,95,98,100

  - protein:
      id: C
      sequence: 6
