entities:
  - file:
      path: /home/chenxq/boltzgen_me/LEADS-PEP_inputfiles/4DGY/4DGY_clean_protein.pdb
      include:
        - chain:
            id: H
      binding_types:
        - chain:
            id: H
            binding: 47,50,52,56,58,98,100

  - protein:
      id: B
      sequence: 12
