entities:
  - file:
      path: /home/chenxq/boltzgen_me/LEADS-PEP_inputfiles/4J44/4J44_clean_protein.pdb
      include:
        - chain:
            id: A
      binding_types:
        - chain:
            id: A
            binding: 197,206,207,208,209,210,211,214,219,222,223,224

  - protein:
      id: B
      sequence: 4
